[package]
name = "protec"
version = "0.1.0"
edition = "2024"

[dependencies]
clearscreen = "4.0.2"
viuer = { version = "0.11.0", features = ["print-file"] }
libc = "0.2.180"
ctrlc = { version = "3.5.1",features = ["termination"] }
termios = "0.3.3"
